CREATE TABLE `parsikea2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cat` text NOT NULL,
  `sku` varchar(16) NOT NULL,
  `url` text NOT NULL,
  `img` text NOT NULL,
  `desc` text NOT NULL,
  `fulldesc` longtext NOT NULL,
  `title` text NOT NULL,
  `name` text NOT NULL,
  `qant` text NOT NULL,
  `price` text NOT NULL,
  `widh` text NOT NULL,
  `height` text NOT NULL,
  `lenght` text NOT NULL,
  `weight` text NOT NULL,
  `isset` text NOT NULL,
  `releted` text NOT NULL,
  `inserted` int(11) NOT NULL,
  `other_mod_sku` text,
  `crumbs` text,
  `cat_entry_id` varchar(32) DEFAULT NULL,
  `main_cat_entry_id` varchar(32) DEFAULT NULL,
  `attr_select` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_sku` (`sku`) USING BTREE,
  KEY `idx_cat_entry_id` (`cat_entry_id`),
  KEY `idx_main_cat_entry_id` (`main_cat_entry_id`)
) ENGINE=MyISAM AUTO_INCREMENT=13262 DEFAULT CHARSET=utf8
